export const BannerTypes = {
  CLICK_LEON_BANNER: 'CLICK_LEON_BANNER',
  CLICK_META_TOKENS_BANNER: 'CLICK_META_TOKENS_BANNER',
  CLICK_FUTURE_PLAY_BANNER: 'CLICK_FUTURE_PLAY_BANNER',
  CLICK_GYDDE_BANNER: 'CLICK_GYDDE_BANNER',
} as const;
