import { ROUTES_NAME } from '@core/constants/Routes';

export const ROUTER_LINKS = {
  GAME: `${ROUTES_NAME.ROOT}`,
  REFERRALS: `${ROUTES_NAME.ROOT}${ROUTES_NAME.REFERRALS}`,
  EARN: `${ROUTES_NAME.ROOT}${ROUTES_NAME.EARN}`,
  LEADERBOARD: `${ROUTES_NAME.ROOT}${ROUTES_NAME.LEADERBOARD}`,
  METAMASK: `${ROUTES_NAME.ROOT}${ROUTES_NAME.METAMASK}`,
  ACCOUNT_ABSTRACTION: `${ROUTES_NAME.ROOT}${ROUTES_NAME.ACCOUNT_ABSTRACTION}`,
} as const;
