import METAMASK from './metamask';

export const FEATURE_TOGGLES = {
  METAMASK: {
    ENABLED:  METAMASK.ENABLED,
    ROUTES_NAME: METAMASK.ROUTES_NAME
  },
  ACCOUNT_ABSTRACTION: {
    ENABLED: import.meta.env.VITE_ACCOUNT_ABSTRACTION_FEATURE_TOGGLE === 'true'
  }
} as const;

export const FEATURE_TOGGLES_ROUTES_NAME = {
  ...FEATURE_TOGGLES.METAMASK.ROUTES_NAME,
  ACCOUNT_ABSTRACTION: 'wallet'
};
